Fix multiply addon price by nights opiton
woocommerce/woocommerce-accommodation-bookings pull request #228
Opened 2019-10-10 00:58 UTC by superdav42

Fixes https://github.com/woocommerce/woocommerce-product-addons/issues/489
and https://github.com/woocommerce/woocommerce-product-addons/issues/489
and https://github.com/woocommerce/woocommerce-product-addons/issues/485

#### Changes proposed in this Pull Request:
- Stop having accommodations duplicate code of the bookings integration.
- Option "Multiply cost number of nights" is the same as "Multiply cost by block count" but it'll just be renamed in accommodations.
- So now these options actually work
- Also fix displaying the options correctly before product is created.

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

2019-10-10 12:30 UTC, Ferdev requested changes
Cannot get this to work. I don't have this commit in the branch it's mentioned in this PR. Actually, this PR uses the same branch as another PR I've just reviewed: https://github.com/woocommerce/woocommerce-bookings/pull/2700.

I created an accommodations product, min nights 1, max nights 5. $25 flat free addon with "Bookings: Multiply cost by number of nights" and the block price is $100. I booked three nights and the cost was $325. If my calculations are correct, it should have be $375: 3*$100 + $25*3.

2019-10-10 20:15 UTC, superdav42 commented
@Ferdev flat fee price type is not multiplied by number of night even with the option checked. You must use quantity based or percentage. It seem to be a common assumption that I just added a tooltip next to the option saying this. Perhaps that's not enough?

2019-10-14 08:52 UTC, Ferdev commented
Oh yes, you're right @superdav42! I didn't know it worked like that. To be honest, I didn't notice the tooltip. Maybe it would be worth it to hide and uncheck that option whenever `flat fee` is selected?

2019-10-14 08:52 UTC, Ferdev approved these changes

2019-10-14 15:51 UTC, superdav42 commented
> Oh yes, you're right @superdav42! I didn't know it worked like that. To be honest, I didn't notice the tooltip. Maybe it would be worth it to hide and uncheck that option whenever `flat fee` is selected?

Hiding or unchecking won't work because it's possible to have multiple options for each field and the options could have different price types. So a merchant could setup one option to be flat and another to be quantity based and they would need to enable this setting.

Documentation is the best way to address this I think.

2019-10-14 15:51 UTC, merged