Add product unit filter to add night unit support
woocommerce/woocommerce-accommodation-bookings pull request #333
Opened 2023-04-06 15:48 UTC by kirtangajjar

### All Submissions:

### Changes proposed in this Pull Request:

Filter product unit to add night unit support.

Closes #320.

### How to test the changes in this Pull Request:

1. Create an Accommodations Booking Product.
2. Set the minimum duration to two or more nights, the maximum to a short range as well.
3. Navigate to the front end and view your product
4. Select a number of days under or over the allowed range
5. Note that the message refers to the duration_unit as "Nights", not "Blocks".

### Changelog entry

> Add product unit filter to add night unit support

2023-04-10 19:45 UTC, dkotter commented
@kirtangajjar Is this one ready for code review?

2023-04-11 10:09 UTC, faisal-alvi requested changes
Added feedback at https://github.com/woocommerce/woocommerce-bookings/pull/3564#pullrequestreview-1378867304, which would require changes in this PR too.

2023-04-11 10:09 UTC, faisal-alvi commented on includes/admin/class-wc-accommodation-booking-admin-panels.php
> +		}
At this point, we would get the value already filtered through the `_n` function from [here](https://github.com/woocommerce/woocommerce-bookings/blob/d37b2fc423aa077ed3ef154b1ebe8f1587a1f9c6/includes/data-objects/class-wc-product-booking.php#L2421).

However, we're still filtering back through the `_n` with the new values (i.e. `night`, `nights`). But seems reasonable.

2023-04-14 10:46 UTC, kirtangajjar commented on includes/admin/class-wc-accommodation-booking-admin-panels.php
> +		}
Yes, that's true; we could've saved a function call if we tried to filter just those two values but for the sake of simplicity of implementation, I liked using this approach.

2023-04-14 12:47 UTC, faisal-alvi approved these changes

2023-05-16 12:42 UTC, ankitguptaindia commented
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.2 
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.7.0
* PHP: 8.0.22
* Web Server: Nginx
* Browser: Chrome - Version 113
* OS: macOS Monterey V 12.3.1
* Git Branch:  fix/320 & fix/accomodation-booking-320  of https://github.com/woocommerce/woocommerce-bookings/pull/3564 

</Details>


**Test Results -** 

Upon selecting a number of days under or over the allowed range, the system displayed a message referring to the duration unit as "Nights," not "Blocks." The message accurately reflects the configured duration unit.

Additionally, the test was performed on other places where the duration appears, such as the checkout page, order page, emails, and booking page. Newly added/updated string found as translatable as well. 


**Functional Demo /  Screencast -**

![Screenshot 2023-05-16 at 6 10 13 PM](https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/6384299/e69d7192-5892-4977-9074-ebb5a8775742)

![Screenshot 2023-05-16 at 6 10 36 PM](https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/6384299/3c7f8490-6713-41cc-bf71-99901af3e235)






**Next Step-** Ready to Code Review(Woo)

2023-05-16 12:42 UTC, ankitguptaindia approved these changes

2023-05-16 12:45 UTC, ankitguptaindia commented
@dkotter Does this PR require assigning Woo team to review? this looks like a simple change.

2023-05-16 12:53 UTC, faisal-alvi approved these changes

2023-05-17 10:22 UTC, faisal-alvi commented
@ankitguptaindia yes we can move this straight to UAT once QA test passes.

2023-05-26 09:41 UTC, ankitguptaindia commented
**Regression+Smoke Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.2.2
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.7.0
* PHP: 8.0.22 
* Web Server: Nginx
* Browser: Chrome - Version 113


</Details>


Tested with Archive File created via 

```php woorelease.phar build https://github.com/woocommerce/woocommerce-accommodation-bookings/tree/smoke-testing```

- Composer version - 2.3.5
- npm version - 6.14.14
- node version - 14.17.5

#### Please note that this plugin is tested with the build created by specified versions of Composer, Node, and NPM. 



**Status-** Ready to Merge 🚀

2023-05-26 13:56 UTC, merged