Fix/363 - Fatal Error when WooCommerce is disabled
woocommerce/woocommerce-accommodation-bookings pull request #367
Opened 2023-09-04 10:13 UTC by faisal-alvi

### All Submissions:

* [ ] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:

This PR adds a check if the `WooCommerce` class exists, if not, it shows a message. This is inspired by the bookings' [message](https://github.com/woocommerce/woocommerce-bookings/blob/abe6d802b7508fe1598406d2cf2143013ad68264/woocommerce-bookings.php#L43).

Closes #363.

### How to test the changes in this Pull Request:

1. Activate WC, WC Booking and Accommodation-Bookings.
2. Deactivate WC
3. A message should appear at the top.
<img width="707" alt="image" src="https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/25176325/7e039a79-01bb-41fc-9130-c1a3bebe6c25">

### Other information:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

> Fix - Fatal Error when WooCommerce is disabled.

2023-09-05 15:08 UTC, dkotter requested changes

2023-09-05 15:08 UTC, dkotter commented on includes/class-wc-accommodation-bookings-plugin.php
> +	public function woocommerce_accommodation_bookings_missing_wc_notice() {
Minor thing but because we are in the `WC_Accommodation_Bookings_Plugin` class, we don't need the prefix on this method name. I'd suggest we change this to be just `missing_wc_notice`

2023-09-06 14:01 UTC, dkotter approved these changes

2023-09-12 14:22 UTC, ankitguptaindia commented
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.3.1
* Theme: Storefront Version: 4.5.2
* WooCommerce - Version 8.0.3
* PHP: 8.0.21 
* Web Server: Nginx
* Browser: Chrome - Version 116
* OS: macOS Monterey V 12.3.1
* Git Branch: fix/363

</Details>



**Test Results -**  Issue has been fixed. 


**Next Step-** Ready to ~~Code Review(Woo)~~ UAT

2023-09-12 14:22 UTC, ankitguptaindia approved these changes

2023-09-18 19:34 UTC, dkotter commented on includes/class-wc-accommodation-bookings-plugin.php
> +	 * @since x.x.x
```suggestion
	 * @since 1.2.1
```

2023-09-29 14:47 UTC, ankitguptaindia commented
**Regression+Smoke Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.3.1
* Theme: Storefront Version: 4.5.2
* WooCommerce - Version 8.1.1
* PHP: 8.0.22 
* Web Server: Nginx
* Browser: Chrome - Version 115


</Details>


Tested with Archive File created via 

```php woorelease.phar build smoke-testing branch _URL_ ```

- Composer version - 2.3.5
- npm version - 8.19.3
- node version - 16.19.1

#### Please note that this plugin has been tested with the build created by the specified versions ☝🏼 of Composer, Node, and NPM. 



**Status-**  Working as expected. Ready to merge 🚀

2023-10-06 17:06 UTC, merged