upkeep/369: PHPCS and PHPCompatibility GH Actions for PHP 7.4+
woocommerce/woocommerce-accommodation-bookings pull request #370
Opened 2023-09-12 14:28 UTC by faisal-alvi

### All Submissions:

* [ ] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:

* Used the same GitHub action with the same PHPCS config (rules) which is used for all extensions when opening a PR
* Checking support for PHP 7.4+
* Checking all PHPCS rules only changed lines in the PR
* Check only the PHPCompatibility rule for all files in the PR
* Validate PHPCS checks passing before merging a PR

Closes #369.

### How to test the changes in this Pull Request:

All the GitHub Actions should be passed.

### Other information:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

> Tweak - Update PHPCS and PHPCompatibility GitHub Actions

2023-09-13 19:05 UTC, dkotter reviewed
Overall this looks good but I don't think we should be bumping our minimum PHP version here. I believe the goal is to still ensure our minimum PHP version matches the minimum PHP version of the minimum Woo version we support (which is still 7.3). The know the linked issue and the P2 post mention 7.4 but I'd suggest we stick with 7.3 for now

2023-09-18 14:06 UTC, dkotter commented on .github/workflows/qit.yml
> +          php-version: 7.3
This needs to stay at 7.4, as that's the minimum required for QIT
```suggestion
          php-version: 7.4
```

2023-09-18 14:10 UTC, dkotter approved these changes

2023-09-19 21:17 UTC, dkotter requested changes

2023-09-19 21:17 UTC, dkotter commented on .gitattributes
> +phpcs.xml.dist export-ignore
We probably want to exclude the PHPCS compat config as well I think

2023-09-19 21:17 UTC, dkotter commented on composer.json
> +		"sirbrillig/phpcs-changed": "^2.11.1",
Looks like spacing is a bit off here

2023-09-19 21:17 UTC, dkotter commented on phpcs-compat.xml.dist
> +	<arg name="extensions" value="php"/>
Looks like spacing is a bit off here

2023-09-20 14:06 UTC, dkotter approved these changes

2023-09-25 16:03 UTC, jeffpaul commented on .github/workflows/phpcs.yml
> +        uses: tj-actions/changed-files@v35
Shouldn't this be changed lines and not changed files?

2023-09-25 16:06 UTC, dkotter commented on .github/workflows/phpcs.yml
> +        uses: tj-actions/changed-files@v35
It uses the `changed-files` action to get a list of changed files and then passes those files into the `phpcs-changed` package (line 50 in this file) which then pulls the changed lines out of those files

2023-10-03 09:50 UTC, faisal-alvi commented
Just added a new commit to bump `woocommerce-sniffs` to `1.0.0` ([internal slack discussion link](https://10up.slack.com/archives/C01UCQGPBDJ/p1696260699336079?thread_ts=1696009651.377169&cid=C01UCQGPBDJ))

2023-10-06 17:07 UTC, merged