Allows product accommodation tabs ordering (priority)
woocommerce/woocommerce-accommodation-bookings pull request #447
Opened 2024-07-08 21:19 UTC by axi

### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:
Last 2 items couldn't be ordered because they were added in '`woocommerce_product_write_panel_tabs`' action hook.
![](https://i.imgur.com/VdH74J0.png)

There's another way to add entries in this menu, by using '`woocommerce_product_data_tabs`' filter hook and this filter allows ordering of the tabs with the priority.
![](https://i.imgur.com/lk7VnEd.png)

### Steps to test the changes in this Pull Request:
in function.php
```
add_filter(
    'woocommerce_product_data_tabs',
    static function (array $tabs) {
        $tabs['doesnt_matter'] = [
            'label'    => 'This one should appear last',
            'target'   => 'doesnt_matter',
            'class'    => [],
            'priority' => 1500, //"Get more options" priority is 1000
        ];

        return $tabs;
    }
);
```

Without the fix:
![](https://i.imgur.com/ouacunZ.png)

With the fix:
![](https://i.imgur.com/MQ3b9NL.png)

### Changelog entry
> Fix - Allows product Accommodation tabs ordering (priority).

2024-07-10 09:39 UTC, faisal-alvi requested changes

2024-07-10 09:39 UTC, faisal-alvi commented on includes/admin/class-wc-accommodation-booking-admin-panels.php
> +			'class'    => array( 'show_if_accommodation-booking', 'bookings_rates_tabs' ),
The tab icons were removed due to a missing class. To prevent functionality breaks like this, all previous classes should be migrated.

2024-07-10 16:36 UTC, axi commented on includes/admin/class-wc-accommodation-booking-admin-panels.php
> +			'class'    => array( 'show_if_accommodation-booking', 'bookings_rates_tabs' ),
Pfff, I should have seen that myself... I even put some screen capture showing it 😅

2024-07-10 17:31 UTC, faisal-alvi approved these changes

2024-07-17 11:19 UTC, ankitguptaindia commented
Thanks, @axi for your contribution to this PR. Functional wise this PR works as interested. Could you please fix the conflict so we can proceed with PR? 

cc: @faisal-alvi

2024-07-17 11:19 UTC, ankitguptaindia approved these changes

2024-07-17 15:38 UTC, axi commented
@ankitguptaindia fixed the conflict, can't fix this:
![image](https://github.com/user-attachments/assets/6c73fd34-1cda-45af-94c8-ae1d10fb0e9b)

2024-07-22 15:00 UTC, ankitguptaindia commented
> @ankitguptaindia fixed the conflict, can't fix this: ![image](https://private-user-images.githubusercontent.com/389340/349564935-6c73fd34-1cda-45af-94c8-ae1d10fb0e9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NjA1NTIsIm5iZiI6MTcyMTY2MDI1MiwicGF0aCI6Ii8zODkzNDAvMzQ5NTY0OTM1LTZjNzNmZDM0LTFjZGEtNDVhZi05NGM4LWFlMWQxMGZiMGU5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNDU3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTUyZTc2NTkyYTI2MmUzZTE0NDYyYjlhMzg0OTQ3OTg1MzE0MGRiZThjNmIwYzEwYjFkZDU5ODRhYWQ4NzBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hKUg9E8QOI-3d-bcN2CVV0fiMN38pylOjxENcwGp1n4)


No problem, this issue is not related to changes in this PR. We are discussing this on another PR.  Thanks, @axi for working on this PR.

2024-08-16 14:01 UTC, ankitguptaindia commented
**Regression+Smoke Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.6.1
* Theme: Storefront Version: 4.6.0
* WooCommerce - Version 9.1.4 
* PHP: 8.3
* Web Server: Nginx
* Browser: Chrome - Version 127
* OS: macOS Sonoma 14.5


</Details>

Tested with Archive File created via woorelease command with: 

- Composer version - v2.3.5
- npm version - v10.1.0
- node version - v20.7.0



**Status-**  Working as expected. Ready to merge 🚀


cc: @vikrampm1

2024-08-16 14:51 UTC, merged